export const FLAGLE_COUNTRY_POOL = [
  'United States', 'Canada', 'Mexico', 'Brazil', 'Argentina', 'Chile', 'Colombia',
  'Peru', 'Venezuela', 'Ecuador', 'Bolivia', 'Paraguay', 'Uruguay', 'Jamaica',
  'Cuba', 'Dominican Republic', 'Haiti', 'Costa Rica', 'Panama', 'Guatemala',
  'Honduras', 'El Salvador', 'Nicaragua', 'Barbados', 'Trinidad and Tobago',
  'United Kingdom', 'France', 'Germany', 'Italy', 'Spain', 'Portugal', 'Netherlands',
  'Belgium', 'Switzerland', 'Austria', 'Sweden', 'Norway', 'Denmark', 'Finland',
  'Iceland', 'Ireland', 'Poland', 'Czech Republic', 'Slovakia', 'Hungary', 'Romania',
  'Bulgaria', 'Greece', 'Croatia', 'Serbia', 'Bosnia and Herzegovina', 'Albania',
  'North Macedonia', 'Montenegro', 'Slovenia', 'Estonia', 'Latvia', 'Lithuania',
  'Belarus', 'Ukraine', 'Moldova', 'Luxembourg', 'Monaco', 'Vatican City',
  'San Marino', 'Andorra', 'Malta', 'Cyprus', 'China', 'Japan', 'South Korea',
  'North Korea', 'India', 'Pakistan', 'Bangladesh', 'Sri Lanka', 'Nepal', 'Bhutan',
  'Afghanistan', 'Thailand', 'Vietnam', 'Cambodia', 'Laos', 'Myanmar', 'Malaysia',
  'Singapore', 'Indonesia', 'Philippines', 'Taiwan', 'Mongolia', 'Kazakhstan',
  'Uzbekistan', 'Turkmenistan', 'Kyrgyzstan', 'Tajikistan', 'Turkey', 'Iran', 'Iraq',
  'Saudi Arabia', 'Yemen', 'Syria', 'Jordan', 'Lebanon', 'Israel', 'Palestine',
  'United Arab Emirates', 'Qatar', 'Kuwait', 'Bahrain', 'Oman', 'Georgia', 'Armenia',
  'Azerbaijan', 'Egypt', 'Libya', 'Tunisia', 'Algeria', 'Morocco', 'Sudan',
  'Ethiopia', 'Kenya', 'Tanzania', 'Uganda', 'Rwanda', 'Burundi', 'Somalia',
  'Nigeria', 'Ghana', 'Ivory Coast', 'Senegal', 'Mali', 'Burkina Faso', 'Niger',
  'Chad', 'Cameroon', 'Central African Republic', 'Democratic Republic of the Congo',
  'Republic of the Congo', 'Gabon', 'Equatorial Guinea', 'Angola', 'Zambia',
  'Zimbabwe', 'Botswana', 'Namibia', 'South Africa', 'Lesotho', 'Eswatini',
  'Mozambique', 'Madagascar', 'Mauritius', 'Seychelles', 'Comoros', 'Cape Verde',
  'Guinea', 'Guinea-Bissau', 'Liberia', 'Sierra Leone', 'Togo', 'Benin',
  'Mauritania', 'Gambia', 'Malawi', 'Eritrea', 'Djibouti', 'South Sudan', 'Australia',
  'New Zealand', 'Papua New Guinea', 'Fiji', 'Solomon Islands', 'Vanuatu', 'Samoa',
  'Tonga', 'Kiribati', 'Tuvalu', 'Nauru', 'Palau', 'Marshall Islands', 'Micronesia',
];

export const FLAGLE_DIFFICULTY_TIERS = {
  easy: [
    'United States', 'Canada', 'United Kingdom', 'France', 'Germany', 'Italy',
    'Spain', 'Japan', 'China', 'Brazil', 'Mexico', 'Australia', 'India', 'Russia',
    'South Korea', 'Argentina', 'Netherlands', 'Switzerland', 'Sweden', 'Norway',
    'Belgium', 'Portugal', 'Greece', 'Turkey', 'Egypt', 'South Africa', 'Israel',
    'Saudi Arabia', 'New Zealand', 'Ireland',
  ],
  medium: [
    'Poland', 'Czech Republic', 'Austria', 'Denmark', 'Finland', 'Iceland',
    'Ukraine', 'Romania', 'Hungary', 'Chile', 'Colombia', 'Peru', 'Venezuela',
    'Thailand', 'Vietnam', 'Indonesia', 'Philippines', 'Malaysia', 'Singapore',
    'Pakistan', 'Bangladesh', 'Nigeria', 'Kenya', 'Morocco', 'Algeria', 'Cuba',
    'Jamaica', 'Croatia', 'Serbia', 'Bulgaria', 'Lithuania', 'Latvia', 'Estonia',
    'Lebanon', 'Jordan', 'United Arab Emirates', 'Qatar', 'Kuwait',
  ],
  hard: [
    'Bosnia and Herzegovina', 'North Macedonia', 'Montenegro', 'Slovenia',
    'Moldova', 'Belarus', 'Georgia', 'Armenia', 'Azerbaijan', 'Kazakhstan',
    'Uzbekistan', 'Kyrgyzstan', 'Tajikistan', 'Turkmenistan', 'Mongolia', 'Myanmar',
    'Laos', 'Cambodia', 'Sri Lanka', 'Nepal', 'Bhutan', 'Mauritius', 'Seychelles',
    'Fiji', 'Papua New Guinea', 'Vanuatu', 'Bahrain', 'Oman', 'Yemen', 'Libya',
    'Tunisia', 'Sudan', 'Ethiopia', 'Tanzania', 'Uganda', 'Rwanda', 'Ghana',
    'Ivory Coast', 'Senegal', 'Cameroon', 'Angola', 'Zimbabwe', 'Botswana',
    'Namibia', 'Mozambique',
  ],
};
