export default [
  {
    path: '/minecraft',
    name: 'Minecraft',
    component: () => import('@/features/minecraft/components/MinecraftDashboard.vue'),
    meta: {
      requiresAuth: true,
      role: null,
      title: 'Minecraft Ops',
      drawerRanking: 1,
      drawerVisible: true,
      layout: 'default',
      description: 'Minecraft server operations.',
      badge: '',
      requiresOverlay: false,
    },
  },
  {
    path: '/minecraft/dashboard',
    name: 'MinecraftDashboard',
    redirect: '/minecraft',
    meta: {
      requiresAuth: true,
      role: null,
      title: 'Minecraft Ops',
      drawerRanking: 1,
      drawerVisible: false,
      layout: 'default',
      description: 'Minecraft server operations.',
      badge: '',
      requiresOverlay: false,
    },
  },
  {
    path: '/minecraft/setup',
    name: 'MinecraftSetup',
    redirect: '/minecraft',
    meta: {
      requiresAuth: true,
      role: null,
      title: 'Minecraft Ops',
      drawerRanking: 1,
      drawerVisible: false,
      layout: 'default',
      description: 'Minecraft server operations.',
      badge: '',
      requiresOverlay: false,
    },
  },
  {
    path: '/minecraft/:id',
    name: 'MinecraftInstance',
    component: () => import('@/features/minecraft/components/MinecraftInstance.vue'),
    meta: {
      requiresAuth: true,
      role: null,
      title: 'Minecraft Server',
      drawerRanking: 1,
      drawerVisible: false,
      layout: 'default',
      description: 'Minecraft server detail.',
      badge: '',
      requiresOverlay: false,
    },
  },
]
