import { ROLES } from '@/shared/constants/roles'

export const personalUnauthorizedRedirect = '/personal/unauthorized'

export default [
    {
        path: '/personal',
        name: 'Personal',
        component: () => import('@/features/personal/views/Personal.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Personal',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'A place to log your personal activities.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/tracker',
        name: 'Tracker',
        component: () => import('@/features/personal/views/Tracker.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Eating Tracker',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'default',
            description: 'Track food, drinks, and other items you eat.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/dare-shame',
        name: 'Dare Shame',
        component: () => import('@/features/personal/views/DareShame.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Dare Tracker',
            drawerRanking: 3,
            drawerVisible: true,
            layout: 'default',
            description: 'Track wasted money, dreams and promises.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/journal',
        name: 'Cozy Journal',
        component: () => import('@/features/personal/views/Journal.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Cozy Journal',
            drawerRanking: 4,
            drawerVisible: true,
            layout: 'default',
            description: 'Get a hand journalling with prompts from ai.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/notes',
        name: 'PersonalNotes',
        component: () => import('@/features/personal/views/Notes.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Notes App',
            drawerRanking: 4,
            drawerVisible: true,
            layout: 'default',
            description: 'Basic notes app.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/kanban',
        name: 'PersonalKanban',
        component: () => import('@/features/personal/views/Kanban.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Kanban Boards',
            drawerRanking: 5,
            drawerVisible: true,
            layout: 'default',
            description: 'Organize tasks with kanban boards.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/kanban/board/:boardId',
        name: 'PersonalKanbanBoard',
        component: () => import('@/features/personal/components/kanban/Board.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Kanban Board',
            drawerRanking: -1, // Hide from drawer
            drawerVisible: false,
            layout: 'default',
            description: 'View and manage kanban board.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/usage',
        name: 'PersonalUsage',
        component: () => import('@/features/personal/views/Usage.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Usage costs',
            drawerRanking: 4,
            drawerVisible: true,
            layout: 'default',
            description: 'Get an idea for how much using our products costs.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/todo',
        name: 'personal-todo',
        component: () => import('@/features/personal/views/GoblinTodoView.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: "Today's Queue",
            drawerRanking: 4,
            drawerVisible: true,
            layout: 'default',
            description: 'Your daily task plate — pull from the queue, track progress, and take notes.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/todo/settings',
        name: 'personal-todo-settings',
        component: () => import('@/features/personal/views/GoblinTodoSettingsView.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Task Queue — Settings',
            drawerRanking: 4,
            drawerVisible: false,
            layout: 'default',
            description: 'Manage custom task statuses and permanent tags for your queue.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/todo/days',
        name: 'personal-todo-days',
        component: () => import('@/features/personal/views/GoblinTodoDaysView.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Task Queue — Timeline',
            drawerRanking: 4,
            drawerVisible: false,
            layout: 'default',
            description: 'A day-by-day history of your task queue with completion heatmap.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/todo/day/:date',
        name: 'personal-todo-day',
        component: () => import('@/features/personal/views/GoblinTodoPastDayView.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Task Queue — Past Day',
            drawerRanking: 4,
            drawerVisible: false,
            layout: 'default',
            description: 'Review tasks and notes from a previous day.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/todo/tasks',
        name: 'personal-todo-tasks',
        component: () => import('@/features/personal/views/GoblinTodoAllTasksView.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Task Queue — All Tasks',
            drawerRanking: 4,
            drawerVisible: false,
            layout: 'default',
            description: 'Browse, filter, and manage every task across all statuses.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/todo/task/:id',
        name: 'personal-todo-task',
        component: () => import('@/features/personal/views/GoblinTodoTaskView.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Task Queue — Task History',
            drawerRanking: 4,
            drawerVisible: false,
            layout: 'default',
            description: "View a task's full lifetime — events, days on plate, and linked notes.",
            badge: '',
            requiresOverlay: false,
        },
    },
]