import { ROLES } from '@/shared/constants/roles'

export default [
    {
        path: '/everhomes',
        alias: ['/everhomes/'],
        name: 'Everhomes | Tools',
        component: () => import('@/features/everhomes/views/ToolsLandingPage.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Everhomes | Tools',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Select a tool from this page.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/import',
        alias: ['/everhomes/upload'],
        name: 'Everhomes | Import',
        component: () => import('@/features/everhomes/views/ImportWizard.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Everhomes | Import',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Upload spreadsheets and ingest them into the system.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/import/sheets',
        alias: ['/everhomes/import/sheet'],
        name: 'SheetSelector',
        component: () => import('@/features/everhomes/views/import/SelectorSheet.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Everhomes | Import',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Upload spreadsheets and ingest them into the system.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/import/review',
        alias: ['/everhomes/import/table-review'],
        name: 'TableReview',
        component: () => import('@/features/everhomes/views/import/TableReview.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Everhomes | Import',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Upload spreadsheets and ingest them into the system.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/water-bill',
        alias: ['/everhomes/water-bills'],
        name: 'Everhomes | Water Bills',
        component: () => import('@/features/everhomes/views/tools/WaterBills.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Water Bills',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Calculate water bill costs.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/placement-fee',
        alias: ['/everhomes/placement-fees', '/everhomes/placement'],
        name: 'Everhomes | Placement Fees',
        component: () => import('@/features/everhomes/views/tools/PlacementFees.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Placement Fees',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Calculate placement fees.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/sda-returns',
        alias: ['/everhomes/sda-returns', '/everhomes/sda-return'],
        name: 'Everhomes | SDA Returns',
        component: () => import('@/features/everhomes/views/tools/SDAReturns.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'SDA Returns',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Calculate sda returns.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/inspection-checklist',
        alias: ['/everhomes/inspection'],
        name: 'Everhomes | Inspection Checklist',
        component: () => import('@/features/everhomes/views/tools/InspectionChecklist.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Inspection Checklist',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Walk through property rooms and capture photos for each area.',
            badge: 'New',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/handover-checklist',
        alias: ['/everhomes/handover'],
        name: 'Everhomes | Handover Checklist',
        component: () => import('@/features/everhomes/views/tools/HandoverChecklist.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Handover Checklist',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Walk through property rooms and capture photos for each area.',
            badge: 'New',
            requiresOverlay: false,
        },
    }
]
