// src/features/everhomes/routes.js

export default [
    {
        path: '/everhomes',
        alias: ['/everhomes/'],
        name: 'Everhomes | Tools',
        component: () => import('@/features/everhomes/views/ToolsLandingPage.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Everhomes | Tools',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Select a tool from this page.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/import',
        alias: ['/everhomes/upload'],
        name: 'Everhomes | Import',
        component: () => import('@/features/everhomes/views/ImportWizard.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Everhomes | Import',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Upload spreadsheets and ingest them into the system.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/import/sheets',
        alias: ['/everhomes/import/sheet'],
        name: 'SheetSelector',
        component: () => import('@/features/everhomes/views/import/SelectorSheet.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Everhomes | Import',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Upload spreadsheets and ingest them into the system.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/import/review',
        alias: ['/everhomes/import/table-review'],
        name: 'TableReview',
        component: () => import('@/features/everhomes/views/import/TableReview.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Everhomes | Import',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Upload spreadsheets and ingest them into the system.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/water-bill',
        alias: ['/everhomes/water-bills'],
        name: 'Everhomes | Water Bills',
        component: () => import('@/features/everhomes/views/tools/WaterBills.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Water Bills',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Calculate water bill costs.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/placement-fee',
        alias: ['/everhomes/placement-fees', '/everhomes/placement'],
        name: 'Everhomes | Placement Fees',
        component: () => import('@/features/everhomes/views/tools/PlacementFees.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Placement Fees',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Calculate placement fees.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/sda-returns',
        alias: ['/everhomes/sda-returns', '/everhomes/sda-return'],
        name: 'Everhomes | SDA Returns',
        component: () => import('@/features/everhomes/views/tools/SDAReturns.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'SDA Returns',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Calculate sda returns.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },

    // ─── Report page — single route, schema-driven ────────────────────────────
    // ReportPage.vue reads :reportType and loads the matching schema.
    // Adding a new report type = new schema file + a new redirect below.
    {
        path: '/everhomes/report/:reportType',
        name: 'Everhomes | Report',
        component: () => import('@/features/everhomes/views/tools/ReportPage.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Everhomes | Report',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Walk through the property and generate a compliance report.',
            badge: 'New',
            requiresOverlay: false,
        },
    },

    // ─── Legacy / shorthand redirects ────────────────────────────────────────
    // Aliases can't inject params, so these are explicit redirects.
    // Old bookmarks and any existing links continue to work.
    { path: '/everhomes/handover-checklist', redirect: { name: 'Everhomes | Report', params: { reportType: 'handover' } } },
    { path: '/everhomes/handover',           redirect: { name: 'Everhomes | Report', params: { reportType: 'handover' } } },
    { path: '/everhomes/inspection-checklist', redirect: { name: 'Everhomes | Report', params: { reportType: 'inspection' } } },
    { path: '/everhomes/inspection',         redirect: { name: 'Everhomes | Report', params: { reportType: 'inspection' } } },
]