import { ROLES } from '@/constants/roles'

export default [
    {
        path: '/everhomes',
        alias: ['/everhomes/'],
        name: 'Everhomes | Tools',
        component: () => import('@/pages/everhomes/ToolsLandingPage.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Everhomes | Tools',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Select a tool from this page.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/import',
        alias: ['/everhomes/upload'],
        name: 'Everhomes | Import',
        component: () => import('@/pages/everhomes/ImportPage.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Everhomes | Import',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Upload spreadsheets and ingest them into the system.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/import/sheets',
        alias: ['/everhomes/import/sheet'],
        name: 'SheetSelector',
        component: () => import('@/pages/everhomes/import/SelectorSheet.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Everhomes | Import',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Upload spreadsheets and ingest them into the system.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/import/review',
        alias: ['/everhomes/import/table-review'],
        name: 'TableReview',
        component: () => import('@/pages/everhomes/import/TableReview.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Everhomes | Import',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Upload spreadsheets and ingest them into the system.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/water-bill',
        alias: ['/everhomes/water-bills'],
        name: 'Everhomes | Water Bills',
        component: () => import('@/pages/everhomes/tools/WaterBills.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Water Bills',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Calculate water bill costs.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/placement-fee',
        alias: ['/everhomes/placement-fees', '/everhomes/placement'],
        name: 'Everhomes | Placement Fees',
        component: () => import('@/pages/everhomes/tools/PlacementFees.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Placement Fees',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Calculate placement fees.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    },
    {
        path: '/everhomes/sda-returns',
        alias: ['/everhomes/sda-returns', '/everhomes/sda-return'],
        name: 'Everhomes | SDA Returns',
        component: () => import('@/pages/everhomes/tools/SDAReturns.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'SDA Returns',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Calculate sda returns.',
            badge: 'Beta',
            requiresOverlay: false,
        },
    }
]
