// src/routers/modules/mainRoutes.js
import { ROLES } from '@/constants/roles'

// REMOVED: import ComingSoon from '@/pages/MXNHome.vue'
// This was loading MXNHome.vue eagerly even though you're using lazy loading below!

export default [
    {
        path: '/',
        name: 'MXNHome',
        component: () => import('@/pages/MXNHome.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'MXN Home',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'Page under construction.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/core-defense',
        name: 'CoreDefense',
        component: () => import('@/pages/CoreDefense.vue'),
        meta: {
            requiresAuth: false,
            title: 'Core Defense',
            layout: 'default',
        },
    },
    {
        path: '/satisfactory',
        name: 'Satisfactory',
        component: () => import('@/pages/satisfactory/SatisfactorySchematic.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Satisfactory',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'Page under construction.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/bg',
        name: 'BackgroundPreview',
        component: () => import('@/components/common/backgrounds/BackgroundPreview.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'MXN Home',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'Page under construction.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/qr',
        name: 'QRGenerator',
        component: () => import('@/pages/MXNQR.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'QR Generator',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'Page under construction.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/cod',
        name: 'CamoTracker',
        component: () => import('@/pages/cod/CamoTracker.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'MXN COD',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'Page under construction.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/cod/admin',
        name: 'CODAdmin',
        component: () => import('@/pages/cod/WeaponAdmin.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'MXN COD',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'Page under construction.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/daily',
        name: 'MXNDaily',
        component: () => import('@/pages/MXNDaily.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'MXN Daily',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'Page under construction.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/casino',
        name: 'Casino',
        component: () => import('@/pages/casino/Casino.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'MXN Casino',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'Page under construction.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/casino/blackjack',
        name: 'Blackjack',
        component: () => import('@/pages/casino/Blackjack.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'MXN Blackjack',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'Page under construction.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/casino/roulette',
        name: 'Roulette',
        component: () => import('@/pages/casino/Roulette.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'MXN Roulette',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'Page under construction.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/login',
        name: 'TempestID',
        component: () => import('@/pages/system/Login.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Tempest ID Login',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'Use your TempestID to login.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/unauth',
        name: 'Unauthorized',
        component: () => import('@/pages/system/Unauthorized.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Unauthorized',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'You do not have access to view this page.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/ext/login',
        name: 'ExtensionTempestID',
        component: () => import('@/pages/extensions/Login.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Tempest ID Login',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'Page under construction.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/404',
        name: '404',
        component: () => import('@/pages/system/Error404.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: '404 Not Found',
            drawerVisible: false,
            layout: 'default',
            description: 'Page not found.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/:pathMatch(.*)*',
        name: 'NotFoundCatchAll',
        redirect: '/404',
    }
]