import { ROLES } from '@/constants/roles'

export const personalUnauthorizedRedirect = '/personal/unauthorized'

export default [
    {
        path: '/personal',
        name: 'Personal',
        component: () => import('@/pages/personal/Personal.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Personal',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'A place to log your personal activities.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/tracker',
        name: 'Tracker',
        component: () => import('@/pages/personal/Tracker.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Eating Tracker',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'default',
            description: 'Track food, drinks, and other items you eat.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/dare-shame',
        name: 'Dare Shame',
        component: () => import('@/pages/personal/DareShame.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Dare Tracker',
            drawerRanking: 3,
            drawerVisible: true,
            layout: 'default',
            description: 'Track wasted money, dreams and promises.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/journal',
        name: 'Cozy Journal',
        component: () => import('@/pages/personal/Journal.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Cozy Journal',
            drawerRanking: 4,
            drawerVisible: true,
            layout: 'default',
            description: 'Get a hand journalling with prompts from ai.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/notes',
        name: 'PersonalNotes',
        component: () => import('@/pages/personal/Notes.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Notes App',
            drawerRanking: 4,
            drawerVisible: true,
            layout: 'default',
            description: 'Basic notes app.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/kanban',
        name: 'PersonalKanban',
        component: () => import('@/pages/personal/Kanban.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Kanban Boards',
            drawerRanking: 5,
            drawerVisible: true,
            layout: 'default',
            description: 'Organize tasks with kanban boards.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/kanban/board/:boardId',
        name: 'PersonalKanbanBoard',
        component: () => import('@/components/personal/kanban/Board.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Kanban Board',
            drawerRanking: -1, // Hide from drawer
            drawerVisible: false,
            layout: 'default',
            description: 'View and manage kanban board.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/usage',
        name: 'PersonalUsage',
        component: () => import('@/pages/personal/Usage.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Usage costs',
            drawerRanking: 4,
            drawerVisible: true,
            layout: 'default',
            description: 'Get an idea for how much using our products costs.',
            badge: '',
            requiresOverlay: false,
        },
    },
]