import { ROLES } from '@/constants/roles'

export const personalUnauthorizedRedirect = '/personal/unauthorized'

export default [
    {
        path: '/personal',
        name: 'Personal',
        component: () => import('@/pages/personal/Personal.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Personal',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'A place to log your personal activities.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/login',
        name: 'Personal Login',
        component: () => import('@/pages/personal/Login.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Personal Login',
            drawerVisible: false,
            layout: 'default',
            description: 'Log in.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/signup',
        name: 'Personal Sign up',
        component: () => import('@/pages/personal/SignUp.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Personal Sign up',
            drawerVisible: false,
            layout: 'default',
            description: 'Sign up.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/unauthorized',
        name: 'Personal Unauthorized',
        component: () => import('@/pages/personal/Unauthorized.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Personal Unauthorized',
            drawerVisible: false,
            layout: 'default',
            description: 'Unauthorized user.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/tracker',
        name: 'Tracker',
        component: () => import('@/pages/personal/Tracker.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Eating Tracker',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'default',
            description: 'Track food, drinks, and other items you eat.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/personal/dare-shame',
        name: 'Dare Shame',
        component: () => import('@/pages/personal/DareShame.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Dare Tracker',
            drawerRanking: 3,
            drawerVisible: true,
            layout: 'default',
            description: 'Track wasted money, dreams and promises.',
            badge: '',
            requiresOverlay: false,
        },
    },
]