export default [
    // --- Professional Landing Page (Public) ---
    {
        path: '/professional',
        name: 'Professional',
        component: () => import('@/pages/professional/ProfessionalLanding.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Professional Suite',
            drawerRanking: 0,
            drawerVisible: false,
            layout: 'default',
            description: 'Professional suite for small business management.',
            badge: '',
            requiresOverlay: false,
        },
    },

    // --- Dashboard ---
    {
        path: '/professional/home',
        name: 'Professional - Dashboard',
        component: () => import('@/pages/professional/ProfessionalDashboard.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Dashboard',
            icon: 'Home',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'professional',
            description: 'Dashboard with statistics and quick actions.',
            badge: '',
            requiresOverlay: false,
        },
    },

    // --- Company Settings ---
    {
        path: '/professional/company',
        name: 'Professional - Company',
        component: () => import('@/pages/professional/CompanySettings.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Company',
            icon: 'Building2',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'professional',
            description: 'Manage company information, logo, bank details and branding.',
            badge: '',
            requiresOverlay: false,
        },
    },

    // --- Contacts ---
    {
        path: '/professional/contacts',
        name: 'Professional - Contacts',
        component: () => import('@/pages/professional/ContactsList.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Contacts',
            icon: 'Users',
            drawerRanking: 3,
            drawerVisible: true,
            layout: 'professional',
            description: 'Manage your clients and vendors.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/professional/contacts/new',
        name: 'Professional - New Contact',
        component: () => import('@/pages/professional/ContactForm.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'New Contact',
            drawerRanking: 0,
            drawerVisible: false,
            layout: 'professional',
            description: 'Add a new client or vendor contact.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/professional/contacts/:id/edit',
        name: 'Professional - Edit Contact',
        component: () => import('@/pages/professional/ContactForm.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Edit Contact',
            drawerRanking: 0,
            drawerVisible: false,
            layout: 'professional',
            description: 'Edit contact information.',
            badge: '',
            requiresOverlay: false,
        },
    },

    // --- Jobs / Projects ---
    {
        path: '/professional/jobs',
        name: 'Professional - Jobs',
        component: () => import('@/pages/professional/JobsList.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Jobs',
            icon: 'FolderKanban',
            drawerRanking: 4,
            drawerVisible: true,
            layout: 'professional',
            description: 'Manage projects and jobs.',
            badge: 'activeJobs',
            requiresOverlay: false,
        },
    },
    {
        path: '/professional/jobs/new',
        name: 'Professional - New Job',
        component: () => import('@/pages/professional/JobForm.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'New Job',
            drawerRanking: 0,
            drawerVisible: false,
            layout: 'professional',
            description: 'Create a new job or project.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/professional/jobs/:id',
        name: 'Professional - View Job',
        component: () => import('@/pages/professional/JobView.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Job Details',
            drawerRanking: 0,
            drawerVisible: false,
            layout: 'professional',
            description: 'View job details, expenses and invoices.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/professional/jobs/:id/edit',
        name: 'Professional - Edit Job',
        component: () => import('@/pages/professional/JobForm.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Edit Job',
            drawerRanking: 0,
            drawerVisible: false,
            layout: 'professional',
            description: 'Edit job details.',
            badge: '',
            requiresOverlay: false,
        },
    },

    // --- Expenses ---
    {
        path: '/professional/expenses',
        name: 'Professional - Expenses',
        component: () => import('@/pages/professional/ExpensesList.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Expenses',
            icon: 'Receipt',
            drawerRanking: 5,
            drawerVisible: true,
            layout: 'professional',
            description: 'Track and manage business expenses.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/professional/expenses/new',
        name: 'Professional - New Expense',
        component: () => import('@/pages/professional/ExpenseForm.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'New Expense',
            drawerRanking: 0,
            drawerVisible: false,
            layout: 'professional',
            description: 'Add a new expense.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/professional/expenses/:id/edit',
        name: 'Professional - Edit Expense',
        component: () => import('@/pages/professional/ExpenseForm.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Edit Expense',
            drawerRanking: 0,
            drawerVisible: false,
            layout: 'professional',
            description: 'Edit expense details.',
            badge: '',
            requiresOverlay: false,
        },
    },

    // --- Catalogue ---
    {
        path: '/professional/catalogue',
        name: 'Professional - Catalogue',
        component: () => import('@/pages/professional/CatalogueList.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Catalogue',
            icon: 'Package',
            drawerRanking: 6,
            drawerVisible: true,
            layout: 'professional',
            description: 'Product and service catalogue.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/professional/catalogue/new',
        name: 'Professional - New Catalogue Item',
        component: () => import('@/pages/professional/CatalogueForm.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'New Item',
            drawerRanking: 0,
            drawerVisible: false,
            layout: 'professional',
            description: 'Add a new catalogue item.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/professional/catalogue/:id/edit',
        name: 'Professional - Edit Catalogue Item',
        component: () => import('@/pages/professional/CatalogueForm.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Edit Item',
            drawerRanking: 0,
            drawerVisible: false,
            layout: 'professional',
            description: 'Edit catalogue item.',
            badge: '',
            requiresOverlay: false,
        },
    },

    // --- Invoices ---
    {
        path: '/professional/invoices',
        name: 'Professional - Invoices',
        component: () => import('@/pages/professional/InvoicesList.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Invoices',
            icon: 'FileText',
            drawerRanking: 7,
            drawerVisible: true,
            layout: 'professional',
            description: 'View and manage all your invoices.',
            badge: 'pendingInvoices',
            requiresOverlay: false,
        },
    },
    {
        path: '/professional/invoices/new',
        name: 'Professional - New Invoice',
        component: () => import('@/pages/professional/InvoiceForm.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'New Invoice',
            drawerRanking: 0,
            drawerVisible: false,
            layout: 'professional',
            description: 'Create a new invoice.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/professional/invoices/:id',
        name: 'Professional - View Invoice',
        component: () => import('@/pages/professional/InvoiceView.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Invoice Details',
            drawerRanking: 0,
            drawerVisible: false,
            layout: 'professional',
            description: 'View and print invoice details.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/professional/invoices/:id/edit',
        name: 'Professional - Edit Invoice',
        component: () => import('@/pages/professional/InvoiceForm.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Edit Invoice',
            drawerRanking: 0,
            drawerVisible: false,
            layout: 'professional',
            description: 'Edit invoice details and line items.',
            badge: '',
            requiresOverlay: false,
        },
    },

    // --- Payment Links ---
    {
        path: '/professional/payments',
        name: 'Professional - Payments',
        component: () => import('@/pages/professional/PaymentLinks.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Payments',
            icon: 'CreditCard',
            drawerRanking: 8,
            drawerVisible: true,
            layout: 'professional',
            description: 'Manage Stripe payment and subscription links.',
            badge: '',
            requiresOverlay: false,
        },
    },

    // --- Settings ---
    {
        path: '/professional/settings',
        name: 'Professional - Settings',
        component: () => import('@/pages/professional/ProfessionalSettings.vue'),
        meta: {
            requiresAuth: true,
            role: null,
            title: 'Settings',
            icon: 'Settings',
            drawerRanking: 9,
            drawerVisible: true,
            layout: 'professional',
            description: 'Customize appearance and preferences.',
            badge: '',
            requiresOverlay: false,
        },
    },

    // --- Test Page ---
    {
        path: '/professional/test',
        name: 'Professional Test',
        component: () => import('@/pages/professional/TestProfessional.vue'),
        meta: {
            requiresAuth: false,
            layout: 'professional',
            title: 'Test Page'
        }
    }
]