import { ROLES } from '@/constants/roles'

export default [
    {
        path: '/topheroes',
        name: 'TopHeroes',
        component: () => import('@/pages/topheroes/TH_Landing.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Home',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'TopHeroes main landing page.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/tools',
        name: 'TopHeroes - Tools',
        component: () => import('@/pages/topheroes/TH_Tools.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Tools',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'default',
            description: 'Collection of TopHeroes utilities and calculators.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/events',
        name: 'TopHeroes - Events',
        component: () => import('@/pages/topheroes/TH_EventGuides.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Guides',
            drawerRanking: 3,
            drawerVisible: true,
            layout: 'default',
            description: 'Guides and event walkthroughs for TopHeroes.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/velaris',
        name: 'TopHeroes - Velaris',
        component: () => import('@/pages/topheroes/velaris/TH_VelarisHome.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Velaris',
            drawerRanking: 4,
            drawerVisible: true,
            layout: 'default',
            description: 'Home page for Velaris faction in TopHeroes.',
            badge: '',
            requiresOverlay: true,
        },
    },

    // --- TopHeroes Admin Home ---
    {
        path: '/topheroes/admin',
        name: 'TopHeroes - Admin',
        component: () => import('@/pages/topheroes/admin/TH_AdminHome.vue'),
        meta: {
            requiresAuth: true,
            role: ROLES.TOPHEROES_ADMIN,
            title: 'Admin Dashboard',
            drawerRanking: 5,
            drawerVisible: true,
            layout: 'admin',
            description: 'TopHeroes Admin panel overview.',
            badge: '',
            requiresOverlay: false,
        },
    },

    // --- TopHeroes Tools ---
    {
        path: '/topheroes/tools/speedups',
        name: 'TopHeroes - Speed-ups',
        component: () => import('@/pages/topheroes/TH_SpeedUps.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Speed Up Calculator',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'Calculate TopHeroes speed-ups efficiently.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/tools/resources',
        name: 'TopHeroes - Resources',
        component: () => import('@/pages/topheroes/TH_ResourceCalculator.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Resource Calculator',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'default',
            description: 'Calculate resource needs in TopHeroes.',
            badge: '',
            requiresOverlay: true,
        },
    },

    // --- Velaris Events ---
    {
        path: '/topheroes/velaris/events',
        name: 'Velaris Events',
        component: () => import('@/pages/topheroes/velaris/TH_VLR_Events.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Velaris Events',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'Velaris special event guides.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/velaris/events/guild-vs-guild/april-2025',
        name: 'Velaris Event - GvG',
        component: () => import('@/pages/topheroes/velaris/events/GvG_April_2025.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'GvG Stats - April 25',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'Guild vs Guild event statistics for Velaris.',
            badge: 'New',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/velaris/events/guild-race/april-2025',
        name: 'Velaris Event - GR',
        component: () => import('@/pages/topheroes/velaris/events/GvG_April_2025.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'GR Stats - April 25',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'Guild Race event statistics for Velaris.',
            badge: 'New',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/velaris/events/guild-vs-guild/workbench',
        name: 'Velaris Event - GvG Workbench',
        component: () => import('@/pages/topheroes/velaris/events/GvG_Workbench.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'GR Stats - April 25',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'Guild Race event statistics for Velaris.',
            badge: 'New',
            requiresOverlay: true,
        },
    },

    // --- TopHeroes Events ---
    {
        path: '/topheroes/events/dark-empire-invasion',
        name: 'TopHeroes - Dark Empire Invasion',
        component: () => import('@/pages/topheroes/events/TH_DarkEmpireInvasion.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Dark Empire Invasion',
            drawerRanking: 3,
            drawerVisible: true,
            layout: 'default',
            description: 'TopHeroes guide for Dark Empire Invasion event.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/events/kingdom-vs-kingdom',
        name: 'TopHeroes - Kingdom vs. Kingdom',
        component: () => import('@/pages/topheroes/events/TH_KingdomVsKingdom.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Kingdom vs. Kingdom',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'default',
            description: 'Guide for TopHeroes Kingdom vs Kingdom event.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/events/guild-race',
        name: 'TopHeroes - Guild Race',
        component: () => import('@/pages/topheroes/events/TH_GuildRace.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Guild Race',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'TopHeroes Guild Race event strategy and tracking.',
            badge: '',
            requiresOverlay: true,
        },
    },

    // --- TopHeroes Admin Extras ---
    {
        path: '/topheroes/admin/signup',
        name: 'TopHeroes - Admin Sign-up',
        component: () => import('@/pages/topheroes/admin/TH_AdminSignUp.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Admin Sign Up',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'auth',
            description: 'Sign up to become a TopHeroes Admin.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/topheroes/admin/castledata',
        name: 'TopHeroes - Admin Castle Data',
        component: () => import('@/pages/topheroes/admin/TH_AdminCastleData.vue'),
        meta: {
            requiresAuth: true,
            role: ROLES.TOPHEROES_ADMIN,
            title: 'Castle Data Input',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'admin',
            description: 'Input and manage castle data for TopHeroes admins.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/topheroes/admin/login',
        name: 'TopHeroes - Admin Login',
        component: () => import('@/pages/topheroes/admin/TH_AdminLogin.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Admin Login',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'auth',
            description: 'Login page for TopHeroes admins.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/topheroes/admin/events/guides/guide-builder',
        name: 'TopHeroes - Guide Builder',
        component: () => import('@/pages/topheroes/events/guides/Builder.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Admin Login',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'auth',
            description: 'Login page for TopHeroes admins.',
            badge: '',
            requiresOverlay: false,
        },
    },
]
