import { ROLES } from '@/constants/roles'

export default [
    {
        path: '/topheroes',
        name: 'TopHeroes',
        component: () => import('@/pages/topheroes/TH_Landing.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Home',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'TopHeroes main landing page.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/tools',
        name: 'TopHeroes - Tools',
        component: () => import('@/pages/topheroes/TH_Tools.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Tools',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'default',
            description: 'Collection of TopHeroes utilities and calculators.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/events',
        name: 'TopHeroes - Events',
        component: () => import('@/pages/topheroes/TH_EventGuides.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Guides',
            drawerRanking: 3,
            drawerVisible: true,
            layout: 'default',
            description: 'Guides and event walkthroughs for TopHeroes.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/velaris',
        name: 'TopHeroes - Velaris',
        component: () => import('@/pages/topheroes/velaris/TH_VelarisHome.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Velaris',
            drawerRanking: 4,
            drawerVisible: true,
            layout: 'default',
            description: 'Home page for Velaris faction in TopHeroes.',
            badge: '',
            requiresOverlay: true,
        },
    },

    // --- TopHeroes Admin Home ---
    {
        path: '/topheroes/admin',
        name: 'TopHeroes - Admin',
        component: () => import('@/pages/topheroes/admin/TH_AdminHome.vue'),
        meta: {
            requiresAuth: true,
            role: ROLES.TOPHEROES_ADMIN,
            title: 'Admin Dashboard',
            drawerRanking: 5,
            drawerVisible: true,
            layout: 'admin',
            description: 'TopHeroes Admin panel overview.',
            badge: '',
            requiresOverlay: false,
        },
    },

    // --- TopHeroes Tools ---
    {
        path: '/topheroes/tools/speedups',
        name: 'TopHeroes - Speed-ups',
        component: () => import('@/pages/topheroes/TH_SpeedUps.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Speed Up Calculator',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'Calculate TopHeroes speed-ups efficiently.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/tools/resources',
        name: 'TopHeroes - Resources',
        component: () => import('@/pages/topheroes/TH_ResourceCalculator.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Resource Calculator',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'default',
            description: 'Calculate resource needs in TopHeroes.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/tools/stars',
        name: 'THStarCalc',
        component: () => import('@/pages/topheroes/TH_CalcStars.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Star Calculator',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'default',
            description: 'Calculate resource needs in TopHeroes.',
            badge: '',
            requiresOverlay: true,
        },
    },

    // --- Velaris Events ---
    {
        path: '/topheroes/velaris/events',
        name: 'Velaris Events',
        component: () => import('@/pages/topheroes/velaris/TH_VLR_Events.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Velaris Events',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'Velaris special event guides.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/velaris/admin',
        name: 'Velaris Admin',
        component: () => import('@/pages/topheroes/velaris/admin/AdminDashboard.vue'),
        meta: {
            requiresAuth: true,
            role: ROLES.TOPHEROES_ADMIN,
            title: 'Velaris Admin',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Velaris special event guides.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/velaris/admin/members',
        name: 'Velaris Admin | Members',
        component: () => import('@/pages/topheroes/velaris/admin/Members.vue'),
        meta: {
            requiresAuth: true,
            role: ROLES.TOPHEROES_ADMIN,
            title: 'Velaris Admin | Members',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Velaris special event guides.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/velaris/admin/events',
        name: 'Velaris Admin | Events',
        component: () => import('@/pages/topheroes/velaris/admin/Events.vue'),
        meta: {
            requiresAuth: true,
            role: ROLES.TOPHEROES_ADMIN,
            title: 'Velaris Admin | Events',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Velaris special event guides.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/velaris/admin/events/:eventId/edit',
        name: 'Velaris Admin | Edit Event',
        component: () => import('@/pages/topheroes/velaris/admin/events/Edit.vue'),
        meta: {
            requiresAuth: true,
            role: ROLES.TOPHEROES_ADMIN,
            title: 'Edit Event',
            drawerRanking: 1,
            drawerVisible: false,
            layout: 'default',
            description: 'Edit event data.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/velaris/events/:eventId',
        name: 'Velaris Dynamic Event',
        component: () => import('@/pages/topheroes/velaris/events/GvG_Event.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Event Details',
            drawerRanking: null,
            drawerVisible: false,
            layout: 'default',
            description: 'Dynamic Guild vs Guild event statistics for Velaris.',
            badge: 'Dynamic',
            requiresOverlay: true,
        },
    },

    // --- TopHeroes Events ---
    {
        path: '/topheroes/events/dark-empire-invasion',
        name: 'TopHeroes - Dark Empire Invasion',
        component: () => import('@/pages/topheroes/events/TH_DarkEmpireInvasion.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Dark Empire Invasion',
            drawerRanking: 3,
            drawerVisible: true,
            layout: 'default',
            description: 'TopHeroes guide for Dark Empire Invasion event.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/events/kingdom-vs-kingdom',
        name: 'TopHeroes - Kingdom vs. Kingdom',
        component: () => import('@/pages/topheroes/events/TH_KingdomVsKingdom.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Kingdom vs. Kingdom',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'default',
            description: 'Guide for TopHeroes Kingdom vs Kingdom event.',
            badge: '',
            requiresOverlay: true,
        },
    },
    {
        path: '/topheroes/events/guild-race',
        name: 'TopHeroes - Guild Race',
        component: () => import('@/pages/topheroes/events/TH_GuildRace.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Guild Race',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'default',
            description: 'TopHeroes Guild Race event strategy and tracking.',
            badge: '',
            requiresOverlay: true,
        },
    },

    // --- TopHeroes Admin Extras ---
    {
        path: '/topheroes/admin/castledata',
        name: 'TopHeroes - Admin Castle Data',
        component: () => import('@/pages/topheroes/admin/TH_AdminCastleData.vue'),
        meta: {
            requiresAuth: true,
            role: ROLES.TOPHEROES_ADMIN,
            title: 'Castle Data Input',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'admin',
            description: 'Input and manage castle data for TopHeroes admins.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/topheroes/admin/events/guides/guide-builder',
        name: 'TopHeroes - Guide Builder',
        component: () => import('@/pages/topheroes/events/guides/Builder.vue'),
        meta: {
            requiresAuth: false,
            role: ROLES.TOPHEROES_ADMIN,
            title: 'Guide Builder',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'auth',
            description: 'Guide building page for TopHeroes admins.',
            badge: '',
            requiresOverlay: false,
        },
    },
]
