import { ROLES } from '@/constants/roles'

export default [
    {
        path: '/translate',
        name: 'Translate',
        component: () => import('@/pages/translate/Translate.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Translate Dashboard',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'admin',
            description: 'Use the realtime translation app, powered by Open AI.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/translate/legal',
        name: 'TranslateLegal',
        component: () => import('@/pages/translate/Legal.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Translate Legal',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'admin',
            description: 'Terms of Service and Privacy Policy for the MXNTranslate platform.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/translate/bot',
        name: 'TranslateBot',
        component: () => import('@/pages/translate/TR_Landing.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Translate Bot',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'admin',
            description: 'Manage Discord bot translations and translation services.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/translate/usage',
        name: 'TranslateUsage',
        component: () => import('@/pages/translate/TranslateUsage.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Translate Usage',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'admin',
            description: 'View your usage stats and global usage stats for the AI powered translation app.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/translate/bot/login',
        name: 'BotLogin',
        component: () => import('@/pages/translate/bot/Login.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Bot Login',
            drawerVisible: false,
            layout: 'admin',
            requiresOverlay: false,
        },
    },
    {
        path: '/translate/bot/dashboard',
        name: 'BotDashboard',
        component: () => import('@/pages/translate/bot/Dashboard.vue'),
        meta: {
            requiresAuth: false,
            title: 'Bot Dashboard',
            drawerVisible: false,
            layout: 'admin',
            requiresOverlay: false,
        },
    },
    {
        path: '/translate/bot/config/:serverId',
        name: 'BotConfig',
        component: () => import('@/pages/translate/bot/Config.vue'),
        meta: {
            requiresAuth: false,
            title: 'Server Configuration',
            drawerVisible: false,
            layout: 'admin',
            requiresOverlay: false,
        },
    }
]