import { ROLES } from '@/constants/roles'

export default [
    {
        path: '/translate',
        name: 'Translate',
        component: () => import('@/pages/translate/Translate.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Translate Dashboard',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'admin',
            description: 'Use the realtime translation app, powered by Open AI.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/translate/legal',
        name: 'TranslateLegal',
        component: () => import('@/pages/translate/Legal.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Translate Legal',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'admin',
            description: 'Terms of Service and Privacy Policy for the MXNTranslate platform.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/translate/bot',
        name: 'TranslateBot',
        component: () => import('@/pages/translate/TR_Landing.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Translate Bot',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'admin',
            description: 'Manage Discord bot translations and translation services.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/translate/bot/dashboard',
        name: 'TranslateBotDashboard',
        component: () => import('@/pages/translate/DiscordBotHome.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Translate Bot',
            drawerRanking: 2,
            drawerVisible: true,
            layout: 'admin',
            description: 'Manage Discord bot translations and translation services.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/translate/usage',
        name: 'TranslateUsage',
        component: () => import('@/pages/translate/TranslateUsage.vue'),
        meta: {
            requiresAuth: false,
            role: null,
            title: 'Translate Usage',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'admin',
            description: 'View your usage stats and global usage stats for the AI powered translation app.',
            badge: '',
            requiresOverlay: false,
        },
    },
    {
        path: '/translate/rebuild',
        name: 'TranslateRebuild',
        component: () => import('@/pages/translate/RebuildAdminPage.vue'),
        meta: {
            requiresAuth: true,
            role: ROLES.TRANSLATE_ADMIN,
            title: 'Translate Rebuild',
            drawerRanking: 1,
            drawerVisible: true,
            layout: 'admin',
            description: 'View your usage stats and global usage stats for the AI powered translation app.',
            badge: '',
            requiresOverlay: false,
        },
    },
]
